# Use Python image as base
FROM python:latest

# Set working directory
WORKDIR /app

# Copy and install dependencies
COPY backend/requirements.txt .
RUN pip install -r requirements.txt

# Copy the rest of the backend application
COPY backend/ .

# Expose port 8000
EXPOSE 8000

# Command to run Gunicorn server
CMD ["gunicorn", "--bind", "0.0.0.0:8000", "backend.wsgi:application"]
